CC=icpc
CFLAGS=-O0

all:
	$(CC) $(CFLAGS) -I$(HOME)/include/  parentheses.cpp -o parentheses 
	$(CC) $(CFLAGS) -I$(HOME)/include/  parentheses1.cpp -o parentheses1 
	$(CC) $(CFLAGS) -I$(HOME)/include/  parentheses2.cpp -o parentheses2 
clean:
	rm -rf parentheses1
	rm -rf parentheses2
	rm -rf parentheses
